import type { Metadata } from "next";

import type { ILayout } from "types";


export const metadata: Metadata = {
  title: "Bio Sync",
  description: "Generated by create-t3-app",
};


export default function LandingPageLayout(
  { children }: ILayout
) {
  return (
    <>{children}</>
  );
}
