import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Bio Sync",
  description: "Generated by create-t3-app",
};


export default function LandingPageLayout(
  { children }: ILayout
) {
  return (
    <>{children}</>
  );
}
