import { type Metadata } from "next"

import type { ILayout } from "types"


export const metadata: Metadata = {
  title: 'Sign In to Bio Sync',
  description: 'Generated by Next.js',
}

export default function SignInLayout(
  { children }: ILayout
) {
  return (
    <>{children}</>
  )
}
